//This file is generated by VisualGDB and is used to get accurate IntelliSense
#pragma once
#include <Arduino.h>

#define SYSPROGS_ARDUINO_EXPAND_GENERATED_PROTOTYPES \
	void Timer1DisEnable(byte ON1_OFF0, unsigned long PeriodMilis = 1000); \
	void setup(); \
	void int0(); \
	void RassvetZakat(); \
	void loop(); \

